language: node_js
node_js: 16
os: linux
install: skip

jobs:
  include:
    - os: linux
      stage: build
      install: yarn
      script: yarn build
      # https://docs.travis-ci.com/user/using-workspaces/
      workspaces:
        create:
          name: shared
          paths:
            - node_modules
            - target
            - flow-typed
            - typings
            - docs

    - &test
      stage: test
      os: linux
      node_js: 12
      script: yarn test:unit
      workspaces:
        use: shared

    - <<: *test
      node_js: 14

    - <<: *test
      node_js: 16
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - yarn test:report
      after_script:
        - ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

    - stage: release
      if: branch = master AND type != pull_request
      workspaces:
        use: shared
      script: npx -p @qiwi/semrel-toolkit semrel -e @qiwi/semrel-config
