# This is a Github Workflow that runs tests on any push or pull request.
# If the tests pass and this is a push to the master branch it also runs Semantic Release.
name: CI
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Fetch deps
        run: yarn

      - name: Build target
        run: yarn build

      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ github.run_id }}
          retention-days: 1
          path: |
            docs
            target
            flow-typed
            typings
            buildstamp.json

  test_push:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Restore artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact-${{ github.run_id }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Yarn install
        run: |
          sudo apt-get install -y moreutils
          yarn

      - name: Unit tests
        # https://github.com/facebook/jest/issues/12740
        run: |
          yarn test
          sed 's/src\/src/src/g' coverage/lcov.info | sponge coverage/lcov.info

      - name: Update coverage
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ github.run_id }}
          retention-days: 1
          path: |
            coverage
            .nyc_output

  test_pr:
    if: github.event_name == 'pull_request'
    needs: build
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        node-version: [ 16, 18 ]
    name: Test (Node v${{ matrix.node-version }}, OS ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Restore artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact-${{ github.run_id }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - name: Test only
        if: matrix.node-version != '18' || matrix.os != 'ubuntu-22.04'
        run: yarn test

      - name: Test & push coverage
        if: matrix.node-version == '18' && matrix.os == 'ubuntu-22.04'
        run: yarn test

  release:
    name: Release
    # https://github.community/t/trigger-job-on-tag-push-only/18076
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: test_push
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Restore artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact-${{ github.run_id }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Codeclimate
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage/*.lcov:lcov

      - name: Semantic Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
        run: npm_config_yes=true npx zx-semrel
